-- NAJAF ULTRA production data model for Supabase.
-- Run this whole file in Supabase SQL Editor.

create extension if not exists pgcrypto;

create table if not exists public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  full_name text,
  phone text,
  avatar_url text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.addresses (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  label text not null default 'Home',
  address_text text not null,
  city text default 'Bengaluru',
  state text default 'Karnataka',
  country text default 'India',
  pincode text,
  lat double precision,
  lng double precision,
  is_default boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.menu_items (
  id integer primary key,
  name text not null,
  category text not null,
  price integer not null check (price >= 0),
  rating numeric(2,1),
  prep_minutes integer default 20,
  image_url text,
  description text,
  active boolean not null default true
);

create table if not exists public.orders (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  status text not null default 'payment_pending',
  payment_status text not null default 'pending',
  subtotal integer not null,
  delivery_fee integer not null default 0,
  total integer not null,
  razorpay_order_id text unique,
  razorpay_payment_id text,
  address_id uuid references public.addresses(id) on delete set null,
  address_snapshot jsonb not null default '{}'::jsonb,
  destination_lat double precision,
  destination_lng double precision,
  rider_name text default 'Ayaan',
  rider_phone text,
  rider_lat double precision,
  rider_lng double precision,
  rider_heading double precision,
  eta_minutes integer,
  status_updated_at timestamptz not null default now(),
  created_at timestamptz not null default now()
);

create table if not exists public.order_items (
  id uuid primary key default gen_random_uuid(),
  order_id uuid not null references public.orders(id) on delete cascade,
  menu_item_id integer references public.menu_items(id) on delete restrict,
  name text not null,
  unit_price integer not null,
  quantity integer not null check (quantity > 0),
  created_at timestamptz not null default now()
);

create table if not exists public.order_events (
  id bigint generated by default as identity primary key,
  order_id uuid not null references public.orders(id) on delete cascade,
  event_type text not null,
  message text,
  metadata jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

insert into public.menu_items (id, name, category, price, rating, prep_minutes, description, image_url) values
(1, 'Midnight Truffle', 'Pizza', 449, 4.9, 24, 'Smoked mozzarella, truffle cream, roasted mushroom.', 'https://images.unsplash.com/photo-1574071318508-1cdbab80d002?auto=format&fit=crop&w=1200&q=88'),
(2, 'NOVA Smash', 'Burgers', 329, 4.8, 19, 'Double seared patty, house sauce, crisp lettuce.', 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=1200&q=88'),
(3, 'Meteor Fries', 'Sides', 189, 4.7, 16, 'Crisp fries, smoked salt, signature neon dip.', 'https://images.unsplash.com/photo-1573080496219-bb080dd4f877?auto=format&fit=crop&w=1200&q=88'),
(4, 'Saffron Cloud', 'Rice', 389, 4.9, 27, 'Long-grain rice, saffron, roasted vegetables.', 'https://images.unsplash.com/photo-1512058564366-18510be2db19?auto=format&fit=crop&w=1200&q=88'),
(5, 'Tandoori Halo', 'Wraps', 279, 4.8, 21, 'Charred paneer, mint crema, pickled onion.', 'https://images.unsplash.com/photo-1626700051175-6818013e1d4f?auto=format&fit=crop&w=1200&q=88'),
(6, 'Galaxy Momo', 'Snacks', 239, 4.9, 18, 'Steamed momos, chili crunch, sesame glaze.', 'https://images.unsplash.com/photo-1496116218417-1a781b1c416c?auto=format&fit=crop&w=1200&q=88'),
(7, 'Lunar Ramen', 'Noodles', 419, 4.8, 25, 'Silky broth, noodles, corn, scallion, chili oil.', 'https://images.unsplash.com/photo-1569718212165-3a8278d5f624?auto=format&fit=crop&w=1200&q=88'),
(8, 'Comet Shake', 'Drinks', 219, 4.7, 12, 'Vanilla cream, berry ripple, chilled sparkle.', 'https://images.unsplash.com/photo-1572490122747-3968b75cc699?auto=format&fit=crop&w=1200&q=88'),
(9, 'Orbit Tacos', 'Mexican', 299, 4.8, 20, 'Crisp shell, smoky beans, salsa verde.', 'https://images.unsplash.com/photo-1551504734-5ee1c4a1479b?auto=format&fit=crop&w=1200&q=88'),
(10, 'Nebula Brownie', 'Desserts', 199, 4.9, 14, 'Fudgy brownie, sea salt, warm chocolate center.', 'https://images.unsplash.com/photo-1564355808539-22fda35bed7?auto=format&fit=crop&w=1200&q=88')
on conflict (id) do update set name=excluded.name, category=excluded.category, price=excluded.price, rating=excluded.rating, prep_minutes=excluded.prep_minutes, description=excluded.description, image_url=excluded.image_url;

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = public
as $$
begin
  insert into public.profiles (id, full_name)
  values (new.id, coalesce(new.raw_user_meta_data->>'full_name', split_part(new.email, '@', 1)))
  on conflict (id) do nothing;
  return new;
end;
$$;

drop trigger if exists on_auth_user_created on auth.users;
create trigger on_auth_user_created
after insert on auth.users
for each row execute procedure public.handle_new_user();

alter table public.profiles enable row level security;
alter table public.addresses enable row level security;
alter table public.menu_items enable row level security;
alter table public.orders enable row level security;
alter table public.order_items enable row level security;
alter table public.order_events enable row level security;

drop policy if exists "profiles_select_own" on public.profiles;
create policy "profiles_select_own" on public.profiles for select using (auth.uid() = id);
drop policy if exists "profiles_insert_own" on public.profiles;
create policy "profiles_insert_own" on public.profiles for insert with check (auth.uid() = id);
drop policy if exists "profiles_update_own" on public.profiles;
create policy "profiles_update_own" on public.profiles for update using (auth.uid() = id) with check (auth.uid() = id);

drop policy if exists "addresses_select_own" on public.addresses;
create policy "addresses_select_own" on public.addresses for select using (auth.uid() = user_id);
drop policy if exists "addresses_insert_own" on public.addresses;
create policy "addresses_insert_own" on public.addresses for insert with check (auth.uid() = user_id);
drop policy if exists "addresses_update_own" on public.addresses;
create policy "addresses_update_own" on public.addresses for update using (auth.uid() = user_id) with check (auth.uid() = user_id);
drop policy if exists "addresses_delete_own" on public.addresses;
create policy "addresses_delete_own" on public.addresses for delete using (auth.uid() = user_id);

drop policy if exists "menu_public_read" on public.menu_items;
create policy "menu_public_read" on public.menu_items for select using (active = true);

drop policy if exists "orders_select_own" on public.orders;
create policy "orders_select_own" on public.orders for select using (auth.uid() = user_id);

drop policy if exists "order_items_select_own" on public.order_items;
create policy "order_items_select_own" on public.order_items for select
using (exists (select 1 from public.orders o where o.id = order_id and o.user_id = auth.uid()));

drop policy if exists "order_events_select_own" on public.order_events;
create policy "order_events_select_own" on public.order_events for select
using (exists (select 1 from public.orders o where o.id = order_id and o.user_id = auth.uid()));

-- Required for Supabase Realtime Postgres Changes subscriptions.
do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'orders'
  ) then
    execute 'alter publication supabase_realtime add table public.orders';
  end if;
end $$;

-- Optional helper view for dashboards.
create or replace view public.my_order_summary as
select
  o.id,
  o.user_id,
  o.status,
  o.payment_status,
  o.total,
  o.eta_minutes,
  o.rider_name,
  o.rider_lat,
  o.rider_lng,
  o.destination_lat,
  o.destination_lng,
  o.address_snapshot,
  o.created_at,
  coalesce(json_agg(oi order by oi.id) filter (where oi.id is not null), '[]'::json) as items
from public.orders o
left join public.order_items oi on oi.order_id = o.id
group by o.id;
